/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.odontologico;

import Fuentes.fuentes;
import java.awt.Color;

/**
 *
 * @author User
 */
public class PrincipalSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalSecretaria
     */
     fuentes tipofuentes;
    public PrincipalSecretaria(java.awt.Frame parent, boolean modal) {
        initComponents();
        tipofuentes = new fuentes();
        //bRegistrarPaciente.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        bActualizarDatos.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        bAgendarCita.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        bAgendarCita1.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        jLabel1.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 20));
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel4, "src/Imagenes/paciente2.JPG");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel5, "src/Imagenes/paciente.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel6, "src/Imagenes/agenda.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/Imagenes/iconu.png");
        bAgendarCita.setBackground(new Color(246,245,244));
        bActualizarDatos.setBackground(new Color(246,245,244));
        bAgendarCita1.setBackground(new Color(246,245,244));
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bActualizarDatos = new javax.swing.JButton();
        bAgendarCita1 = new javax.swing.JButton();
        bAgendarCita = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 160, 160));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, 160));
        jLabel5.getAccessibleContext().setAccessibleParent(jPanel1);

        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 170, 160));

        bActualizarDatos.setBackground(new java.awt.Color(246, 245, 244));
        bActualizarDatos.setText("Registrar Paciente");
        bActualizarDatos.setBorderPainted(false);
        bActualizarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bActualizarDatos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bActualizarDatos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 30));

        bAgendarCita1.setBackground(new java.awt.Color(246, 245, 244));
        bAgendarCita1.setText("Agendar Cita");
        bAgendarCita1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAgendarCita1.setBorderPainted(false);
        bAgendarCita1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bAgendarCita1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(bAgendarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 210, 30));

        bAgendarCita.setBackground(new java.awt.Color(246, 245, 244));
        bAgendarCita.setText("Actualizar Datos");
        bAgendarCita.setBorderPainted(false);
        bAgendarCita.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bAgendarCita.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgendarCitaActionPerformed(evt);
            }
        });
        getContentPane().add(bAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, 30));

        jPanel1.setBackground(new java.awt.Color(246, 245, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Secretaria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 95, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgendarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAgendarCitaActionPerformed

    private void bActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActualizarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrincipalSecretaria dialog = new PrincipalSecretaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizarDatos;
    private javax.swing.JButton bAgendarCita;
    private javax.swing.JButton bAgendarCita1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
